name = "GRSuite"
uuid = "090ec698-01a0-4de4-b9a9-b0520fa6fd58"
authors = ["Zhen Zhong <auroradysis@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]

[compat]
Aqua = "0.8.9"
JET = "0.9.12"
SafeTestsets = "0.1.0"
Test = "1.11.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test", "SafeTestsets"]
